import unittest


class RouteStructureTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        from app import create_app

        cls.app = create_app()
        cls.routes = {
            (str(rule.rule), tuple(sorted(rule.methods - {"HEAD", "OPTIONS"}))): rule.endpoint
            for rule in cls.app.url_map.iter_rules()
        }

    def test_total_route_contract_is_preserved(self):
        self.assertEqual(len(self.routes), 190)

    def test_acr_routes_are_registered(self):
        expected = {
            ("/acr", ("GET",)): "main.investigacoes_acr",
            ("/acr/nova", ("GET", "POST")): "main.nova_investigacao_acr",
            ("/acr/<int:investigacao_id>", ("GET",)): "main.detalhar_investigacao_acr",
            (
                "/acr/<int:investigacao_id>/5-porques",
                ("POST",),
            ): "main.salvar_5_porques_acr",
            (
                "/acr/<int:investigacao_id>/acoes",
                ("POST",),
            ): "main.criar_acao_acr",
        }
        for route_contract, endpoint in expected.items():
            self.assertEqual(self.routes.get(route_contract), endpoint)

    def test_detector_gas_routes_are_registered(self):
        expected = {
            ("/detectores_gas", ("GET",)): "main.detectores_gas",
            ("/detectores_gas/painel", ("GET",)): "main.painel_detectores_gas",
            ("/detectores_gas/movimentacoes", ("GET",)): "main.relatorio_movimentacoes_detectores_gas",
            ("/api/detectores_gas/usuario_rfid", ("POST",)): "main.api_detector_usuario_rfid",
            ("/api/detectores_gas/<int:detector_id>/entregar", ("POST",)): "main.entregar_detector_gas",
            ("/api/detectores_gas/<int:detector_id>/devolver", ("POST",)): "main.devolver_detector_gas",
            ("/detectores_gas/cadastrar", ("POST",)): "main.cadastrar_detector_gas",
            ("/detectores_gas/<int:detector_id>/editar", ("POST",)): "main.editar_detector_gas",
            ("/detectores_gas/<int:detector_id>/inativar", ("POST",)): "main.inativar_detector_gas",
            ("/detectores_gas/<int:detector_id>/reativar", ("POST",)): "main.reativar_detector_gas",
        }
        for route_contract, endpoint in expected.items():
            self.assertEqual(self.routes.get(route_contract), endpoint)

    def test_cost_center_routes_preserve_urls_methods_and_endpoints(self):
        expected = {
            ("/centros_custos", ("GET", "POST")): "main.centros_custos",
            ("/editar_centro/<int:id>", ("GET", "POST")): "main.editar_centro",
            ("/habilitar_centrocusto/<int:id>", ("POST",)): "main.habilitar_centrocusto",
            ("/desabilitar_centrocusto/<int:id>", ("POST",)): "main.desabilitar_centrocusto",
            ("/superintendencias", ("GET", "POST")): "main.superintendencias",
            ("/editar_superintendencia/<int:id>", ("GET", "POST")): "main.editar_superintendencia",
            ("/habilitar_superintendencia/<int:id>", ("POST",)): "main.habilitar_superintendencia",
            ("/desabilitar_superintendencia/<int:id>", ("POST",)): "main.desabilitar_superintendencia",
            ("/origens", ("GET", "POST")): "main.origens",
            ("/editar_origem/<int:id>", ("GET", "POST")): "main.editar_origem",
            ("/desabilitar_origem/<int:id>", ("POST",)): "main.desabilitar_origem",
            ("/habilitar_origem/<int:id>", ("POST",)): "main.habilitar_origem",
            ("/setores", ("GET", "POST")): "main.setores",
            ("/desativar_setor/<int:id>", ("POST",)): "main.desativar_setor",
            ("/reativar_setor/<int:id>", ("POST",)): "main.reativar_setor",
            ("/funcoes", ("GET", "POST")): "main.funcoes",
            ("/desativar_funcao/<int:id>", ("POST",)): "main.desativar_funcao",
            ("/reativar_funcao/<int:id>", ("POST",)): "main.reativar_funcao",
            ("/cargos", ("GET", "POST")): "main.cargos",
            ("/desativar_cargo/<int:id>", ("POST",)): "main.desativar_cargo",
            ("/reativar_cargo/<int:id>", ("POST",)): "main.reativar_cargo",
            ("/tipos_documento", ("GET", "POST")): "main.tipos_documento",
            ("/desativar_tipo_documento/<int:id>", ("POST",)): "main.desativar_tipo_documento",
            ("/reativar_tipo_documento/<int:id>", ("POST",)): "main.reativar_tipo_documento",
            ("/instrutores", ("GET", "POST")): "main.instrutores",
            ("/editar_instrutor/<int:id>", ("POST",)): "main.editar_instrutor",
            ("/alternar_instrutor/<int:id>", ("POST",)): "main.alternar_instrutor",
            ("/matriz_capacitacao", ("GET",)): "main.matriz_capacitacao",
            ("/salvar_procedimento_cargo", ("POST",)): "main.salvar_procedimento_cargo",
            ("/excluir_procedimento_cargo/<int:id>", ("POST",)): "main.excluir_procedimento_cargo",
            ("/adicionar_funcao_cargo", ("POST",)): "main.adicionar_funcao_cargo",
            ("/remover_funcao_cargo/<int:id>", ("POST",)): "main.remover_funcao_cargo",
            ("/adicionar_procedimento_funcao", ("POST",)): "main.adicionar_procedimento_funcao",
            ("/remover_procedimento_funcao/<int:id>", ("POST",)): "main.remover_procedimento_funcao",
            ("/adicionar_setor_cargo", ("POST",)): "main.adicionar_setor_cargo",
            ("/remover_setor_cargo/<int:id>", ("POST",)): "main.remover_setor_cargo",
            ("/adicionar_procedimento_setor", ("POST",)): "main.adicionar_procedimento_setor",
            ("/remover_procedimento_setor/<int:id>", ("POST",)): "main.remover_procedimento_setor",
            ("/listar_matrizes_capacitacao", ("GET",)): "main.listar_matrizes_capacitacao",
            ("/exportar_matriz_capacitacao/<int:cargo_id>", ("GET",)): "main.exportar_matriz_capacitacao",
            ("/verificar_matriz_funcionario", ("GET",)): "main.verificar_matriz_funcionario",
            ("/procedimentos", ("GET", "POST")): "main.procedimentos",
            ("/editar_procedimento/<int:id>", ("GET", "POST")): "main.editar_procedimento",
            ("/nova_revisao_procedimento/<int:id>", ("GET", "POST")): "main.nova_revisao_procedimento",
            ("/historico_revisoes_procedimento/<int:procedimento_id>", ("GET",)): "main.historico_revisoes_procedimento",
            ("/desativar_procedimento/<int:id>", ("POST",)): "main.desativar_procedimento",
            ("/reativar_procedimento/<int:id>", ("POST",)): "main.reativar_procedimento",
            ("/listar_procedimentos", ("GET",)): "main.listar_procedimentos",
            ("/treinamentos_realizados", ("GET", "POST")): "main.treinamentos_realizados",
            ("/listar_treinamentos", ("GET",)): "main.listar_treinamentos",
            ("/editar_treinamento/<int:id>", ("GET", "POST")): "main.editar_treinamento",
            ("/excluir_treinamento/<int:id>", ("POST",)): "main.excluir_treinamento",
            ("/relatorio_treinamentos_realizados", ("GET",)): "main.relatorio_treinamentos_realizados",
            ("/exportar_treinamentos_realizados_excel", ("GET",)): "main.exportar_treinamentos_realizados_excel",
            ("/relatorio_treinamentos_a_vencer", ("GET",)): "main.relatorio_treinamentos_a_vencer",
            ("/exportar_treinamentos_a_vencer_excel", ("GET",)): "main.exportar_treinamentos_a_vencer_excel",
            ("/relatorio_treinamentos_vencidos", ("GET",)): "main.relatorio_treinamentos_vencidos",
            ("/exportar_treinamentos_vencidos_excel", ("GET",)): "main.exportar_treinamentos_vencidos_excel",
            ("/relatorio_treinamentos_pendentes", ("GET",)): "main.relatorio_treinamentos_pendentes",
            ("/exportar_treinamentos_pendentes_excel", ("GET",)): "main.exportar_treinamentos_pendentes_excel",
            ("/lancar_ap", ("GET", "POST")): "main.lancar_ap",
            ("/listar_ap", ("GET",)): "main.listar_ap",
            ("/excluir_ap/<int:id>", ("POST",)): "main.excluir_ap",
            ("/editar_ap/<int:id>", ("POST",)): "main.editar_ap",
            ("/lancar_ifs", ("GET", "POST")): "main.lancar_ifs",
            ("/listar_ifs", ("GET",)): "main.listar_ifs",
            ("/excluir_ifs/<int:id>", ("POST",)): "main.excluir_ifs",
            ("/editar_ifs/<int:id>", ("GET", "POST")): "main.editar_ifs",
            ("/listar_apr", ("GET",)): "main.listar_apr",
            ("/cadastrar_apr", ("POST",)): "main.cadastrar_apr",
            ("/editar_apr/<int:id>", ("POST",)): "main.editar_apr",
            ("/excluir_apr/<int:id>", ("POST",)): "main.excluir_apr",
            ("/tipos_equipamento", ("GET",)): "main.tipos_equipamento",
            ("/cadastrar_tipo_equipamento", ("POST",)): "main.cadastrar_tipo_equipamento",
            ("/editar_tipo_equipamento/<int:id>", ("POST",)): "main.editar_tipo_equipamento",
            ("/inativar_tipo_equipamento/<int:id>", ("POST",)): "main.inativar_tipo_equipamento",
            ("/ativar_tipo_equipamento/<int:id>", ("POST",)): "main.ativar_tipo_equipamento",
            ("/equipamentos", ("GET",)): "main.equipamentos",
            ("/cadastrar_equipamento", ("POST",)): "main.cadastrar_equipamento",
            ("/editar_equipamento/<int:id>", ("POST",)): "main.editar_equipamento",
            ("/inativar_equipamento/<int:id>", ("POST",)): "main.inativar_equipamento",
            ("/ativar_equipamento/<int:id>", ("POST",)): "main.ativar_equipamento",
            ("/pcpm_pessoas", ("GET",)): "main.pcpm_pessoas",
            ("/cadastrar_pcpm_pessoa", ("POST",)): "main.cadastrar_pcpm_pessoa",
            ("/editar_pcpm_pessoa/<int:id>", ("POST",)): "main.editar_pcpm_pessoa",
            ("/inativar_pcpm_pessoa/<int:id>", ("POST",)): "main.inativar_pcpm_pessoa",
            ("/ativar_pcpm_pessoa/<int:id>", ("POST",)): "main.ativar_pcpm_pessoa",
            ("/pcpm_empresas", ("GET",)): "main.pcpm_empresas",
            ("/cadastrar_pcpm_empresa", ("POST",)): "main.cadastrar_pcpm_empresa",
            ("/editar_pcpm_empresa/<int:id>", ("POST",)): "main.editar_pcpm_empresa",
            ("/inativar_pcpm_empresa/<int:id>", ("POST",)): "main.inativar_pcpm_empresa",
            ("/ativar_pcpm_empresa/<int:id>", ("POST",)): "main.ativar_pcpm_empresa",
            ("/api/pcpm/empresas", ("GET",)): "main.api_pcpm_empresas",
            ("/pcpm_checklist_modelos", ("GET",)): "main.pcpm_checklist_modelos",
            ("/cadastrar_pcpm_checklist_modelo", ("POST",)): "main.cadastrar_pcpm_checklist_modelo",
            ("/editar_pcpm_checklist_modelo/<int:id>", ("POST",)): "main.editar_pcpm_checklist_modelo",
            ("/inativar_pcpm_checklist_modelo/<int:id>", ("POST",)): "main.inativar_pcpm_checklist_modelo",
            ("/ativar_pcpm_checklist_modelo/<int:id>", ("POST",)): "main.ativar_pcpm_checklist_modelo",
            ("/pcpm_checklist_itens/<int:modelo_id>", ("GET",)): "main.pcpm_checklist_itens",
            ("/cadastrar_pcpm_checklist_item/<int:modelo_id>", ("POST",)): "main.cadastrar_pcpm_checklist_item",
            ("/editar_pcpm_checklist_item/<int:id>", ("POST",)): "main.editar_pcpm_checklist_item",
            ("/inativar_pcpm_checklist_item/<int:id>", ("POST",)): "main.inativar_pcpm_checklist_item",
            ("/ativar_pcpm_checklist_item/<int:id>", ("POST",)): "main.ativar_pcpm_checklist_item",
            ("/pcpm_movimentacao", ("GET",)): "main.pcpm_movimentacao",
            ("/salvar_pcpm_movimentacao", ("POST",)): "main.salvar_pcpm_movimentacao",
            ("/pcpm_painel_movimentacoes", ("GET",)): "main.pcpm_painel_movimentacoes",
            ("/visualizar_pcpm_movimentacao/<int:movimentacao_id>", ("GET",)): "main.visualizar_pcpm_movimentacao",
            ("/editar_pcpm_movimentacao/<int:movimentacao_id>", ("GET", "POST")): "main.editar_pcpm_movimentacao",
            ("/excluir_pcpm_movimentacao/<int:movimentacao_id>", ("GET",)): "main.excluir_pcpm_movimentacao",
            ("/listar_pcpm_movimentacoes", ("GET",)): "main.listar_pcpm_movimentacoes",
            ("/api/pcpm/teste", ("GET",)): "main.api_pcpm_teste",
            ("/api/pcpm/equipamentos", ("GET",)): "main.api_pcpm_equipamentos",
            ("/api/pcpm/checklist/<int:equipamento_id>", ("GET",)): "main.api_pcpm_checklist",
            ("/api/pcpm/movimentacao", ("POST",)): "main.api_pcpm_salvar_movimentacao",
            ("/api/pcpm/upload_foto", ("POST",)): "main.api_pcpm_upload_foto",
            ("/api/pcpm/cliente/rfid/<rfid>", ("GET",)): "main.api_pcpm_cliente_por_rfid",
            ("/api/pcpm/cliente/cadastrar", ("POST",)): "main.api_pcpm_cadastrar_cliente_app",
            ("/api/pcpm/funcionario/rfid/<rfid>", ("GET",)): "main.api_pcpm_funcionario_por_rfid",
            ("/agendamentos_ssma", ("GET",)): "main.listar_agendamentos_ssma",
            ("/listar_agendamentos_ssma", ("GET",)): "main.listar_agendamentos_ssma",
            ("/novo_agendamento_ssma", ("GET", "POST")): "main.novo_agendamento_ssma",
            ("/excluir_agendamento_ssma/<int:id>", ("POST",)): "main.excluir_agendamento_ssma",
            ("/meu_calendario_ssma", ("GET",)): "main.meu_calendario_ssma",
            ("/executar_agendamento_ssma/<int:id>", ("GET",)): "main.executar_agendamento_ssma",
            ("/relatorio_aderencia_ssma", ("GET",)): "main.relatorio_aderencia_ssma",
            ("/cadastrar_hs", ("GET",)): "main.cadastrar_hs",
            ("/cadastrar_hs/tema", ("POST",)): "main.cadastrar_hs_tema",
            ("/cadastrar_hs/item", ("POST",)): "main.cadastrar_hs_item",
            ("/editar_hs/item/<int:id>", ("GET", "POST")): "main.editar_hs_item",
            ("/habilitar_hs/tema/<int:id>", ("GET",)): "main.habilitar_hs_tema",
            ("/desabilitar_hs/tema/<int:id>", ("GET",)): "main.desabilitar_hs_tema",
            ("/habilitar_hs/item/<int:id>", ("GET",)): "main.habilitar_hs_item",
            ("/desabilitar_hs/item/<int:id>", ("GET",)): "main.desabilitar_hs_item",
            ("/lancar_hs", ("GET", "POST")): "main.lancar_hs",
            ("/editar_hs/<int:id>", ("GET", "POST")): "main.editar_hs",
            ("/excluir_hs/<int:id>", ("POST",)): "main.excluir_hs",
            ("/listar_hs", ("GET",)): "main.listar_hs",
            ("/causas_recusa", ("GET", "POST")): "main.causas_recusa",
            ("/editar_causa/<int:id>", ("GET", "POST")): "main.editar_causa",
            ("/desativar_causa/<int:id>", ("GET",)): "main.desativar_causa",
            ("/ativar_causa/<int:id>", ("GET",)): "main.ativar_causa",
            ("/lancar_recusa", ("GET", "POST")): "main.lancar_recusa",
            ("/editar_recusa/<int:id>", ("GET", "POST")): "main.editar_recusa",
            ("/excluir_recusa/<int:id>", ("POST",)): "main.excluir_recusa",
            ("/listar_recusa", ("GET",)): "main.listar_recusa",
            ("/lancar_reconhecimento", ("GET", "POST")): "main.lancar_reconhecimento",
            ("/listar_reconhecimento", ("GET",)): "main.listar_reconhecimento",
            ("/editar_reconhecimento/<int:id>", ("GET", "POST")): "main.editar_reconhecimento",
            ("/excluir_reconhecimento/<int:id>", ("POST",)): "main.excluir_reconhecimento",
            ("/listar_melhoria", ("GET",)): "main.listar_melhorias",
            ("/lancar_melhoria", ("GET", "POST")): "main.lancar_melhoria",
            ("/editar_melhoria/<int:id>", ("GET", "POST")): "main.editar_melhoria",
            ("/excluir_melhoria/<int:id>", ("GET", "POST")): "main.excluir_melhoria",
            ("/usuarios", ("GET", "POST")): "main.usuarios",
            ("/editar_usuario/<int:id>", ("GET", "POST")): "main.editar_usuario",
            ("/listar_usuarios", ("GET",)): "main.listar_usuarios",
            ("/permissoes_usuario/<int:id>", ("GET", "POST")): "main.permissoes_usuario",
            ("/dashboard", ("GET",)): "main.dashboard",
            ("/cadastrar_acao", ("GET", "POST")): "main.cadastrar_acao",
            ("/editar_acao/<int:id>", ("GET", "POST")): "main.editar_acao",
            ("/excluir_acao/<int:id>", ("GET",)): "main.excluir_acao",
            ("/anexar_evidencia/<int:acao_id>", ("GET", "POST")): "main.anexar_evidencia",
            ("/minhas_acoes", ("GET",)): "main.minhas_acoes",
            ("/acoes_criadas", ("GET",)): "main.acoes_criadas",
            ("/exportar_minhas_acoes", ("GET",)): "main.exportar_minhas_acoes",
            ("/exportar_acoes_criadas", ("GET",)): "main.exportar_acoes_criadas",
            ("/", ("GET",)): "main.index",
            ("/login", ("GET", "POST")): "main.login",
            ("/admin", ("GET",)): "main.admin",
            ("/alterar_senha", ("GET", "POST")): "main.alterar_senha",
            ("/logout", ("GET",)): "main.logout",
            ("/esqueci_senha", ("GET", "POST")): "main.esqueci_senha",
            ("/redefinir_senha/<token>", ("GET", "POST")): "main.redefinir_senha",
            ("/admin/testar_relatorio", ("POST",)): "main.testar_relatorio",
        }
        for contract, endpoint in expected.items():
            with self.subTest(contract=contract):
                self.assertEqual(self.routes.get(contract), endpoint)

    def test_cost_center_endpoints_come_from_views_module(self):
        expected_modules = {
            "main.centros_custos": "app.views.centros_custos",
            "main.editar_centro": "app.views.centros_custos",
            "main.habilitar_centrocusto": "app.views.centros_custos",
            "main.desabilitar_centrocusto": "app.views.centros_custos",
            "main.superintendencias": "app.views.superintendencias",
            "main.editar_superintendencia": "app.views.superintendencias",
            "main.habilitar_superintendencia": "app.views.superintendencias",
            "main.desabilitar_superintendencia": "app.views.superintendencias",
            "main.origens": "app.views.origens",
            "main.editar_origem": "app.views.origens",
            "main.desabilitar_origem": "app.views.origens",
            "main.habilitar_origem": "app.views.origens",
            "main.setores": "app.views.setores",
            "main.desativar_setor": "app.views.setores",
            "main.reativar_setor": "app.views.setores",
            "main.funcoes": "app.views.funcoes",
            "main.desativar_funcao": "app.views.funcoes",
            "main.reativar_funcao": "app.views.funcoes",
            "main.cargos": "app.views.cargos",
            "main.desativar_cargo": "app.views.cargos",
            "main.reativar_cargo": "app.views.cargos",
            "main.tipos_documento": "app.views.tipos_documento",
            "main.desativar_tipo_documento": "app.views.tipos_documento",
            "main.reativar_tipo_documento": "app.views.tipos_documento",
            "main.instrutores": "app.views.instrutores",
            "main.editar_instrutor": "app.views.instrutores",
            "main.alternar_instrutor": "app.views.instrutores",
            "main.matriz_capacitacao": "app.views.matriz_capacitacao",
            "main.salvar_procedimento_cargo": "app.views.matriz_capacitacao",
            "main.excluir_procedimento_cargo": "app.views.matriz_capacitacao",
            "main.adicionar_funcao_cargo": "app.views.matriz_capacitacao",
            "main.remover_funcao_cargo": "app.views.matriz_capacitacao",
            "main.adicionar_procedimento_funcao": "app.views.matriz_capacitacao",
            "main.remover_procedimento_funcao": "app.views.matriz_capacitacao",
            "main.adicionar_setor_cargo": "app.views.matriz_capacitacao",
            "main.remover_setor_cargo": "app.views.matriz_capacitacao",
            "main.adicionar_procedimento_setor": "app.views.matriz_capacitacao",
            "main.remover_procedimento_setor": "app.views.matriz_capacitacao",
            "main.listar_matrizes_capacitacao": "app.views.matriz_capacitacao",
            "main.exportar_matriz_capacitacao": "app.views.matriz_capacitacao",
            "main.verificar_matriz_funcionario": "app.views.matriz_capacitacao",
            "main.procedimentos": "app.views.procedimentos",
            "main.editar_procedimento": "app.views.procedimentos",
            "main.nova_revisao_procedimento": "app.views.procedimentos",
            "main.historico_revisoes_procedimento": "app.views.procedimentos",
            "main.desativar_procedimento": "app.views.procedimentos",
            "main.reativar_procedimento": "app.views.procedimentos",
            "main.listar_procedimentos": "app.views.procedimentos",
            "main.treinamentos_realizados": "app.views.treinamentos",
            "main.listar_treinamentos": "app.views.treinamentos",
            "main.editar_treinamento": "app.views.treinamentos",
            "main.excluir_treinamento": "app.views.treinamentos",
            "main.relatorio_treinamentos_realizados": "app.views.treinamentos",
            "main.exportar_treinamentos_realizados_excel": "app.views.treinamentos",
            "main.relatorio_treinamentos_a_vencer": "app.views.treinamentos",
            "main.exportar_treinamentos_a_vencer_excel": "app.views.treinamentos",
            "main.relatorio_treinamentos_vencidos": "app.views.treinamentos",
            "main.exportar_treinamentos_vencidos_excel": "app.views.treinamentos",
            "main.relatorio_treinamentos_pendentes": "app.views.treinamentos",
            "main.exportar_treinamentos_pendentes_excel": "app.views.treinamentos",
            "main.lancar_ap": "app.views.auditoria_padrao",
            "main.listar_ap": "app.views.auditoria_padrao",
            "main.excluir_ap": "app.views.auditoria_padrao",
            "main.editar_ap": "app.views.auditoria_padrao",
            "main.lancar_ifs": "app.views.ifs",
            "main.listar_ifs": "app.views.ifs",
            "main.excluir_ifs": "app.views.ifs",
            "main.editar_ifs": "app.views.ifs",
            "main.listar_apr": "app.views.apr",
            "main.cadastrar_apr": "app.views.apr",
            "main.editar_apr": "app.views.apr",
            "main.excluir_apr": "app.views.apr",
            "main.tipos_equipamento": "app.views.pcpm_equipamentos",
            "main.cadastrar_tipo_equipamento": "app.views.pcpm_equipamentos",
            "main.editar_tipo_equipamento": "app.views.pcpm_equipamentos",
            "main.inativar_tipo_equipamento": "app.views.pcpm_equipamentos",
            "main.ativar_tipo_equipamento": "app.views.pcpm_equipamentos",
            "main.equipamentos": "app.views.pcpm_equipamentos",
            "main.cadastrar_equipamento": "app.views.pcpm_equipamentos",
            "main.editar_equipamento": "app.views.pcpm_equipamentos",
            "main.inativar_equipamento": "app.views.pcpm_equipamentos",
            "main.ativar_equipamento": "app.views.pcpm_equipamentos",
            "main.pcpm_pessoas": "app.views.pcpm_cadastros",
            "main.cadastrar_pcpm_pessoa": "app.views.pcpm_cadastros",
            "main.editar_pcpm_pessoa": "app.views.pcpm_cadastros",
            "main.inativar_pcpm_pessoa": "app.views.pcpm_cadastros",
            "main.ativar_pcpm_pessoa": "app.views.pcpm_cadastros",
            "main.pcpm_empresas": "app.views.pcpm_cadastros",
            "main.cadastrar_pcpm_empresa": "app.views.pcpm_cadastros",
            "main.editar_pcpm_empresa": "app.views.pcpm_cadastros",
            "main.inativar_pcpm_empresa": "app.views.pcpm_cadastros",
            "main.ativar_pcpm_empresa": "app.views.pcpm_cadastros",
            "main.api_pcpm_empresas": "app.views.pcpm_cadastros",
            "main.pcpm_checklist_modelos": "app.views.pcpm_checklist",
            "main.cadastrar_pcpm_checklist_modelo": "app.views.pcpm_checklist",
            "main.editar_pcpm_checklist_modelo": "app.views.pcpm_checklist",
            "main.inativar_pcpm_checklist_modelo": "app.views.pcpm_checklist",
            "main.ativar_pcpm_checklist_modelo": "app.views.pcpm_checklist",
            "main.pcpm_checklist_itens": "app.views.pcpm_checklist",
            "main.cadastrar_pcpm_checklist_item": "app.views.pcpm_checklist",
            "main.editar_pcpm_checklist_item": "app.views.pcpm_checklist",
            "main.inativar_pcpm_checklist_item": "app.views.pcpm_checklist",
            "main.ativar_pcpm_checklist_item": "app.views.pcpm_checklist",
            "main.pcpm_movimentacao": "app.views.pcpm_movimentacoes",
            "main.salvar_pcpm_movimentacao": "app.views.pcpm_movimentacoes",
            "main.pcpm_painel_movimentacoes": "app.views.pcpm_movimentacoes",
            "main.visualizar_pcpm_movimentacao": "app.views.pcpm_movimentacoes",
            "main.editar_pcpm_movimentacao": "app.views.pcpm_movimentacoes",
            "main.excluir_pcpm_movimentacao": "app.views.pcpm_movimentacoes",
            "main.listar_pcpm_movimentacoes": "app.views.pcpm_movimentacoes",
            "main.api_pcpm_teste": "app.views.pcpm_movimentacoes",
            "main.api_pcpm_equipamentos": "app.views.pcpm_movimentacoes",
            "main.api_pcpm_checklist": "app.views.pcpm_movimentacoes",
            "main.api_pcpm_salvar_movimentacao": "app.views.pcpm_movimentacoes",
            "main.api_pcpm_upload_foto": "app.views.pcpm_movimentacoes",
            "main.api_pcpm_cliente_por_rfid": "app.views.pcpm_movimentacoes",
            "main.api_pcpm_cadastrar_cliente_app": "app.views.pcpm_movimentacoes",
            "main.api_pcpm_funcionario_por_rfid": "app.views.pcpm_movimentacoes",
            "main.listar_agendamentos_ssma": "app.views.agenda_ssma",
            "main.novo_agendamento_ssma": "app.views.agenda_ssma",
            "main.excluir_agendamento_ssma": "app.views.agenda_ssma",
            "main.meu_calendario_ssma": "app.views.agenda_ssma",
            "main.executar_agendamento_ssma": "app.views.agenda_ssma",
            "main.relatorio_aderencia_ssma": "app.views.agenda_ssma",
            "main.cadastrar_hs": "app.views.horas_seguranca",
            "main.cadastrar_hs_tema": "app.views.horas_seguranca",
            "main.cadastrar_hs_item": "app.views.horas_seguranca",
            "main.editar_hs_item": "app.views.horas_seguranca",
            "main.habilitar_hs_tema": "app.views.horas_seguranca",
            "main.desabilitar_hs_tema": "app.views.horas_seguranca",
            "main.habilitar_hs_item": "app.views.horas_seguranca",
            "main.desabilitar_hs_item": "app.views.horas_seguranca",
            "main.lancar_hs": "app.views.horas_seguranca",
            "main.editar_hs": "app.views.horas_seguranca",
            "main.excluir_hs": "app.views.horas_seguranca",
            "main.listar_hs": "app.views.horas_seguranca",
            "main.causas_recusa": "app.views.recusa_tarefa",
            "main.editar_causa": "app.views.recusa_tarefa",
            "main.desativar_causa": "app.views.recusa_tarefa",
            "main.ativar_causa": "app.views.recusa_tarefa",
            "main.lancar_recusa": "app.views.recusa_tarefa",
            "main.editar_recusa": "app.views.recusa_tarefa",
            "main.excluir_recusa": "app.views.recusa_tarefa",
            "main.listar_recusa": "app.views.recusa_tarefa",
            "main.lancar_reconhecimento": "app.views.reconhecimentos",
            "main.listar_reconhecimento": "app.views.reconhecimentos",
            "main.editar_reconhecimento": "app.views.reconhecimentos",
            "main.excluir_reconhecimento": "app.views.reconhecimentos",
            "main.listar_melhorias": "app.views.melhorias",
            "main.lancar_melhoria": "app.views.melhorias",
            "main.editar_melhoria": "app.views.melhorias",
            "main.excluir_melhoria": "app.views.melhorias",
            "main.usuarios": "app.views.usuarios",
            "main.editar_usuario": "app.views.usuarios",
            "main.listar_usuarios": "app.views.usuarios",
            "main.permissoes_usuario": "app.views.usuarios",
            "main.dashboard": "app.views.plano_acao",
            "main.cadastrar_acao": "app.views.plano_acao",
            "main.editar_acao": "app.views.plano_acao",
            "main.excluir_acao": "app.views.plano_acao",
            "main.anexar_evidencia": "app.views.plano_acao",
            "main.minhas_acoes": "app.views.plano_acao",
            "main.acoes_criadas": "app.views.plano_acao",
            "main.exportar_minhas_acoes": "app.views.plano_acao",
            "main.exportar_acoes_criadas": "app.views.plano_acao",
            "main.index": "app.views.autenticacao",
            "main.login": "app.views.autenticacao",
            "main.admin": "app.views.autenticacao",
            "main.alterar_senha": "app.views.autenticacao",
            "main.logout": "app.views.autenticacao",
            "main.esqueci_senha": "app.views.autenticacao",
            "main.redefinir_senha": "app.views.autenticacao",
            "main.testar_relatorio": "app.views.autenticacao",
        }
        for endpoint, expected_module in expected_modules.items():
            with self.subTest(endpoint=endpoint):
                view = self.app.view_functions[endpoint]
                while hasattr(view, "__wrapped__"):
                    view = view.__wrapped__
                self.assertEqual(view.__module__, expected_module)


if __name__ == "__main__":
    unittest.main()
